name: ShellCheck

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          set -euo pipefail
          echo "Linting bash scripts..."
          # Find scripts (exclude potential third-party or build dirs if needed)
          echo "Files:" scripts/bash/*.sh
          shellcheck --severity=style --format=tty --external-sources --check-sourced scripts/bash/*.sh
