name: CI - Build, Test, Coverage & Benchmarks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      os:
        description: 'JSON array of runners'
        type: string
        default: '["ubuntu-latest"]'
        required: true

      dotnet-version:
        description: 'Version of .NET SDK to use'
        type: string
        default: '9.0.x'
        required: true

      test-project:
        description: 'Path to test project'
        type: string
        default: './test/UlidType.Tests/UlidType.Tests.csproj'
        required: true

      coverage-threshold:
        description: 'Minimum acceptable code coverage percentage'
        type: number
        default: 75
        required: true

      run-benchmarks:
        description: 'Whether to run benchmarks and compare against baseline'
        type: boolean
        default: true
        required: true

      benchmark-project:
        description: 'Path to benchmark project'
        type: string
        default: './benchmarks/UlidType.Benchmarks/UlidType.Benchmarks.csproj'
        required: true

      regression-threshold:
        description: 'Maximum acceptable performance regression percentage'
        type: number
        default: 10
        required: true

      force-new-baseline:
        description: 'Whether to force new baseline (if true, no regression check is done)'
        type: boolean
        default: false
        required: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    if: >
      ${{ github.event_name != 'push' ||
          (!contains(github.event.head_commit.message, '[skip ci]')) &&
          (!contains(github.event.head_commit.message, '[no ci]'  ))    }}
    with:
      dotnet-version: ${{ inputs.dotnet-version || vars.DOTNET_VERSION || '9.0.x' }}
      os:             ${{ inputs.os             || vars.MATRIX_OS      || '["ubuntu-latest"]' }}

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      dotnet-version:     ${{ inputs.dotnet-version     || vars.DOTNET_VERSION               || '9.0.x' }}
      os:                 ${{ inputs.os                 || vars.MATRIX_OS                    || '["ubuntu-latest"]' }}
      test-project:       ${{ inputs.test-project       || vars.TEST_PROJECT                 || './test/UlidType.Tests/UlidType.Tests.csproj' }}
      coverage-threshold: ${{ inputs.coverage-threshold || fromJSON(vars.COVERAGE_THRESHOLD) || 75 }}

  benchmarks:
    name: Benchmarks (Linux only)
    needs: build
    if: ${{ inputs.run-benchmarks || fromJSON(vars.RUN_BENCHMARKS) || true }}
    uses: ./.github/workflows/benchmarks.yml
    with:
      dotnet-version:       ${{ inputs.dotnet-version       || vars.DOTNET_VERSION                 || '9.0.x' }}
      benchmark-project:    ${{ inputs.benchmark-project    || vars.BENCHMARK_PROJECT              || './benchmarks/UlidType.Benchmarks/UlidType.Benchmarks.csproj' }}
      force-new-baseline:   ${{ inputs.force-new-baseline   || fromJSON(vars.FORCE_NEW_BASELINE)   || false }}
      regression-threshold: ${{ inputs.regression-threshold || fromJSON(vars.REGRESSION_THRESHOLD) || 10 }}
