name: Clear Caches

# Workflow for manually triggering clearing of caches.
# This is useful when dependabot updates dependencies but the contents of the cache conflicts with the updates,
# e.g., in packages.lock.json files

on:
  workflow_dispatch:
    inputs:

      reason:
        description: 'Reason for clearing cache'
        required: true
        type: string
        default: 'Cache content conflicts with the dependencies'

      cache-pattern:
        description: 'Cache key pattern to delete (e.g.: nuget-)'
        required: false
        type: string
        default: 'nuget-'

permissions:
  actions: write
  contents: read

jobs:
  call_ci:
    name: Call the CI Workflow
    uses: vmelamed/vm2.DevOps/.github/workflows/_clear_cache.yaml@main
    with:
      reason: ${{ inputs.reason }}
      cache-pattern: ${{ inputs.cache-pattern }}
