name: ShellCheck

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          set -euo pipefail
          echo "Linting bash scripts..."
          # Find scripts (exclude potential third-party or build dirs if needed)
          mapfile -t files < <(git ls-files '*.sh' 'scripts/bash/*' ':!:**/bin/**' ':!:**/obj/**')
          if ((${#files[@]} == 0)); then
            echo "No shell scripts found."; exit 0
          fi
          echo "Files:" "${files[@]}"
          shellcheck --severity=style --format=tty "${files[@]}"

      - name: Self-test harness
        run: |
          set -euo pipefail
          chmod +x scripts/bash/self-test.sh
          VERBOSE=1 ./scripts/bash/self-test.sh
