name: Reusable - Test .NET

on:
  workflow_call:
    inputs:
      os:
        description: "Runner OS-s"
        type: string
        required: true
        default: '["ubuntu-latest"]'

      dotnet-version:
        type: string
        required: true
        default: "9.0.x"

      test-project:
        description: "Path to the test project"
        type: string
        required: false
        default: "./test/UlidType.Tests/UlidType.Tests.csproj"

      configuration:
        description: "The type of build to produce, e.g. Release vs Debug"
        type: string
        required: false
        default: "Release"

      define:
        description: "Define constants to pass to the compiler"
        type: string
        required: false
        default: ""

      verbose:
        description: "Whether to enable verbose logging"
        type: boolean
        required: false
        default: false

      min-coverage-pct:
        type: number
        required: true
        default: 75

permissions:
  contents: read

env:
  CI: true  # implies --quiet for the scripts
  VERBOSE: ${{ inputs.verbose || false }} # enables tracing and dump_vars in the scripts
  # these must be the same across all jobs and steps below.
  # We must know where to find the artifacts and where to download/upload to/from across all jobs and steps here.
  ARTIFACTS_DIR: "TestArtifacts"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj

      - name: Make Scripts Executable
        run: chmod u+x ./scripts/bash/*.sh

      - name: Run script for unit test with coverage
        shell: bash
        env:
          VERBOSE: ${{ inputs.verbose || false }}
        run: >-
          ./scripts/bash/run-tests.sh ${{ inputs.test-project }}
          --min-coverage-pct "${{ inputs.min-coverage-pct }}"
          --configuration "${{ inputs.configuration }}"
          --define "${{ inputs.define }}"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: ${{ env.ARTIFACTS_DIR }}
          if-no-files-found: error
          overwrite: true
          retention-days: 5
